document.addEventListener('DOMContentLoaded',function(){
  const main=document.querySelector('main'),header=document.querySelector('.header');
  const path=window.location.pathname;
  const currentLang=path.startsWith('/nl/')?'nl':path.startsWith('/de/')?'de':'en';
  const labels={en:{skip:'Skip to main content',choose:'Choose website language',chat:'Chat with AziBal',menu:'Open menu',close:'Close menu'},nl:{skip:'Ga naar hoofdinhoud',choose:'Kies website-taal',chat:'Chat met AziBal',menu:'Menu openen',close:'Menu sluiten'},de:{skip:'Zum Hauptinhalt',choose:'Website-Sprache wählen',chat:'Mit AziBal chatten',menu:'Menü öffnen',close:'Menü schließen'}};
  if(main&&header&&!document.querySelector('.skip-link')){if(!main.id)main.id='main-content';const skip=document.createElement('a');skip.className='skip-link';skip.href='#'+main.id;skip.textContent=labels[currentLang].skip;document.body.insertBefore(skip,document.body.firstChild)}
  function pageName(){let p=path.replace(/^\/(nl|de)\//,'/');if(p==='/'||p==='/nl/'||p==='/de/')return 'index.html';return p.split('/').filter(Boolean).pop()||'index.html'}
  function targetFor(lang){const page=pageName();if(lang==='en')return page==='index.html'?'/':'/'+page;return page==='index.html'?'/'+lang+'/':'/'+lang+'/'+page}
  if(header&&!document.querySelector('.language-switcher')){
    const style=document.createElement('style');style.textContent='.language-switcher{position:relative;flex:0 0 auto}.language-toggle{width:46px;height:46px;border-radius:50%;border:1px solid #d9dee7;background:#fff;color:#0b1f3a;display:flex;align-items:center;justify-content:center;gap:2px;cursor:pointer;font:800 11px/1 Inter,Arial,sans-serif;box-shadow:0 5px 16px rgba(15,31,58,.06)}.language-toggle:hover{border-color:#c89b3c}.language-toggle:focus-visible{outline:3px solid rgba(200,155,60,.35);outline-offset:3px}.language-icon{font-size:16px}.language-code{font-size:10px}.language-menu{position:absolute;right:0;top:55px;z-index:2200;min-width:158px;padding:7px;background:#fff;border:1px solid #e1e6ee;border-radius:12px;box-shadow:0 16px 38px rgba(7,21,43,.16);display:none}.language-switcher.is-open .language-menu{display:block}.language-menu button{width:100%;border:0;background:transparent;color:#25324a;text-align:left;padding:10px 11px;border-radius:8px;font:700 13px/1.2 Inter,Arial,sans-serif;cursor:pointer}.language-menu button:hover,.language-menu button:focus-visible{background:#f5f7fa;color:#9b7425;outline:none}.language-menu button.is-active{background:#f7f1e5;color:#8a651c}@media(max-width:780px){.language-switcher{margin-left:auto}.language-toggle{width:40px;height:40px}.language-menu{top:47px}}';document.head.appendChild(style);
    const wrap=document.createElement('div');wrap.className='language-switcher';const toggle=document.createElement('button');toggle.type='button';toggle.className='language-toggle';toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label',labels[currentLang].choose);toggle.innerHTML='<span class="language-icon" aria-hidden="true">🌐</span><span class="language-code">'+currentLang.toUpperCase()+'</span>';const menu=document.createElement('div');menu.className='language-menu';menu.setAttribute('role','menu');[['en','English'],['nl','Nederlands'],['de','Deutsch']].forEach(([code,label])=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.setAttribute('role','menuitem');if(code===currentLang)b.classList.add('is-active');b.addEventListener('click',()=>{localStorage.setItem('azibal-language',code);window.location.href=targetFor(code)});menu.appendChild(b)});toggle.addEventListener('click',e=>{e.stopPropagation();const open=wrap.classList.toggle('is-open');toggle.setAttribute('aria-expanded',String(open))});document.addEventListener('click',e=>{if(!wrap.contains(e.target)){wrap.classList.remove('is-open');toggle.setAttribute('aria-expanded','false')}});wrap.append(toggle,menu);const cta=header.querySelector('.header-btn');header.insertBefore(wrap,cta||null)
  }
  if(header&&!document.querySelector('.mobile-menu-toggle')){
    const nav=header.querySelector('.nav');
    const desktopCta=header.querySelector('.header-btn');
    if(nav){
      nav.id=nav.id||'site-navigation';
      const mobileStyle=document.createElement('style');
      mobileStyle.textContent='.mobile-menu-toggle{display:none;width:40px;height:40px;border:1px solid #d9dee7;border-radius:9px;background:#fff;color:#0b1f3a;align-items:center;justify-content:center;cursor:pointer;padding:0}.mobile-menu-toggle span,.mobile-menu-toggle::before,.mobile-menu-toggle::after{content:"";display:block;width:18px;height:2px;background:#0b1f3a;border-radius:2px;transition:transform .2s ease,opacity .2s ease}.mobile-menu-toggle span{margin:4px 0}.mobile-menu-toggle:focus-visible{outline:3px solid rgba(200,155,60,.35);outline-offset:3px}.mobile-nav-cta{display:none!important}@media(max-width:780px){.header{position:sticky!important;top:0!important;flex-wrap:nowrap!important;min-height:68px!important;padding:12px 5%!important}.header>.header-btn{display:none!important}.mobile-menu-toggle{display:block}.header .nav{display:none;position:absolute;left:0;right:0;top:100%;width:100%;padding:12px 5% 18px;background:#fff;border-top:1px solid #e8ebf0;border-bottom:1px solid #e8ebf0;box-shadow:0 14px 26px rgba(15,31,58,.1);flex-direction:column;align-items:stretch;gap:0}.header.is-menu-open .nav{display:flex}.header .nav a{width:100%;padding:11px 4px;font-size:15px;border-bottom:1px solid #f0f2f5}.header .nav a:last-child{border-bottom:0}.header .nav .mobile-nav-cta{display:flex!important;margin-top:12px;padding:12px 16px;border:0;border-radius:8px;background:#c89b3c;color:#fff;justify-content:center}.header.is-menu-open .mobile-menu-toggle::before{transform:translateY(6px) rotate(45deg)}.header.is-menu-open .mobile-menu-toggle span{opacity:0}.header.is-menu-open .mobile-menu-toggle::after{transform:translateY(-6px) rotate(-45deg)}}';
      document.head.appendChild(mobileStyle);
      if(desktopCta&&!nav.querySelector('.mobile-nav-cta')){const mobileCta=desktopCta.cloneNode(true);mobileCta.classList.add('mobile-nav-cta');nav.appendChild(mobileCta)}
      const menuToggle=document.createElement('button');menuToggle.type='button';menuToggle.className='mobile-menu-toggle';menuToggle.setAttribute('aria-controls',nav.id);menuToggle.setAttribute('aria-expanded','false');menuToggle.setAttribute('aria-label',labels[currentLang].menu);menuToggle.innerHTML='<span></span>';
      header.appendChild(menuToggle);
      function closeMobileMenu(){header.classList.remove('is-menu-open');menuToggle.setAttribute('aria-expanded','false');menuToggle.setAttribute('aria-label',labels[currentLang].menu)}
      menuToggle.addEventListener('click',()=>{const open=header.classList.toggle('is-menu-open');menuToggle.setAttribute('aria-expanded',String(open));menuToggle.setAttribute('aria-label',open?labels[currentLang].close:labels[currentLang].menu)});
      nav.addEventListener('click',e=>{if(e.target.closest('a'))closeMobileMenu()});
      document.addEventListener('keydown',e=>{if(e.key==='Escape'&&header.classList.contains('is-menu-open')){closeMobileMenu();menuToggle.focus()}});
      document.addEventListener('click',e=>{if(header.classList.contains('is-menu-open')&&!header.contains(e.target))closeMobileMenu()});
    }
  }
  if(document.getElementById('azibal-chat-launcher'))return;
  const s=document.createElement('style');s.textContent='.az-chat-launcher{position:fixed;right:22px;bottom:22px;z-index:3000;border:0;border-radius:999px;background:#0b1f3a;color:#fff;box-shadow:0 12px 30px rgba(7,21,43,.28);padding:13px 18px;font:700 14px Inter,Arial,sans-serif;cursor:pointer}.az-chat-panel{position:fixed;right:22px;bottom:82px;width:min(360px,calc(100vw - 28px));z-index:3001;background:#fff;border:1px solid #e2e7ee;border-radius:16px;box-shadow:0 22px 55px rgba(7,21,43,.25);display:none;padding:18px;font-family:Inter,Arial,sans-serif}.az-chat-panel.is-open{display:block}.az-chat-panel h3{color:#0b1f3a;margin-bottom:8px}.az-chat-panel p{color:#667085;margin-bottom:12px}.az-chat-panel a{display:inline-block;margin:5px 6px 0 0;padding:8px 10px;border-radius:8px;background:#0b1f3a;color:#fff;text-decoration:none;font-size:12px;font-weight:700}@media(max-width:520px){.az-chat-launcher{right:12px;bottom:12px}.az-chat-panel{right:12px;bottom:68px;width:calc(100vw - 24px)}}';document.head.appendChild(s);
  const launcher=document.createElement('button');launcher.id='azibal-chat-launcher';launcher.className='az-chat-launcher';launcher.type='button';launcher.textContent=labels[currentLang].chat;const panel=document.createElement('div');panel.className='az-chat-panel';const localized=currentLang==='nl'?{title:'AziBal Assistent',text:'Hulp nodig met groothandel, merken, leveranciers of zakelijke aanvragen?',enquiry:'Zakelijke aanvraag',contact:'Contact'}:currentLang==='de'?{title:'AziBal Assistent',text:'Benötigen Sie Hilfe zu Großhandel, Marken, Lieferanten oder Geschäftsanfragen?',enquiry:'Geschäftsanfrage',contact:'Kontakt'}:{title:'AziBal Assistant',text:'Need help with wholesale, brands, suppliers or business enquiries?',enquiry:'Business Enquiry',contact:'Contact'};panel.innerHTML='<h3>'+localized.title+'</h3><p>'+localized.text+'</p><a href="partner-form.html">'+localized.enquiry+'</a><a href="contact.html">'+localized.contact+'</a>';document.body.append(launcher,panel);launcher.addEventListener('click',()=>panel.classList.toggle('is-open'));
});
(function(){const script=document.createElement('script');script.src='/js/newsletter.js';script.async=true;document.head.appendChild(script)})();